image: proboci/ubuntu-16.04-lamp:php7.1-nightly
assets:
  - wpengine_zivtech.sql
steps:
  - name: Site setup
    plugin: WordPressApp
    database: 'wpengine_zivtech.sql'
    databaseName: 'wp_zivtech'
    databaseGzipped: false
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
    flushCaches: true
