image: proboci/ubuntu-16.04-lamp:php-7.1
assets:
  - wpengine_zivtech.sql
steps:
  - name: Test Connection
    plugin: Shell
    command: 'echo "Hello World!"'
  - name: Site setup
    plugin: WordPressApp
    database: 'wpengine_zivtech.sql'
    databaseName: 'wp_zivtech'
    databaseGzipped: false
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
    flushCaches: true
